version: "3.8"
services:
  web:
    image: web:latest-local
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./data:/app/data"
    ports:
      - "${PORT-8000}:8000"
